### ISSUE TITLE
Getting an error on upload

### ISSUE THREAD

**Issue by alorus** [marcosinger/attachment_magick#10]
When I try to upload, I get a dialog box which appears and says "500".  Upon inspecting the log I see this error:

Completed 500 Internal Server Error in 61ms

NoMethodError (undefined method `style_publisher' for #<Class:0x007f86ed76fb80>):
  activerecord (3.2.2) lib/active_record/dynamic_matchers.rb:50:in`method_missing'
  attachment_magick (0.3.3) app/controllers/attachment_magick/images_controller.rb:13:in `create'

My attachment_magick initializer looks like this:

AttachmentMagick.setup do |config|
  config.default_add_partial = '/media/add_image'  # default

  # You can set grid size manually:
  #  config.columns_amount = 16
  #  config.columns_width  = 52
  #  config.gutter         = 8
  # Or with our magick :)
  config.parse_stylesheet('960_24_col.css')

  config.orms = ["ActiveRecord"]

  config.custom_styles do
    publisher "52x"
    largest "512x"
    large "256x"
    medium "128x"
    small "64x"
    smallest "32x"
  end
end

Any ideas what I did wrong?

Thanks in advance for any assistance!

**Comment by marcosinger** [comment]
Hi @alorus! I'll check this ok?
I saw that you aren't using the default partial.. Do you can test this with the default partial, please?

**Comment by lucasrenan** [comment]
@alorus 

first of all, try to include a call to `attachment_magick` method to your model.
we forgot to update the readme doc, sorry.
the code inside "default partial" is calling style_publisher method (it's a custom configuration).
custom configurations are not been applied automatically to models yet.

``` ruby
class Post < ActiveRecord::Base
  include AttachmentMagick

  attachment_magick
end
```

**Comment by alorus** [comment]
Yep that fixed it.  Thanks.
