### ISSUE TITLE
Tamanhos individuais de imagens para cada modelo

### ISSUE THREAD

**Issue by marcosinger** [marcosinger/attachment_magick#3]
Dentro da faixa de grid que pode ser criado com o método privado "generate_grids" podemos atribuir quais tamanhos de image cada modelo precisa.

Com o generate_grids padrão, temos 19 colunas, com 54px de largura e sem espaçamento entre elas. Com isso podemos ter uma classe assim:

<pre><code>class Robocop
  attachment_magick do
    grid_1
    grid_7 :height => 320
    grid_8 :width => 210
    grid_9 "420x110"
  end
end
</code></pre>

O exemplo acima atribui a class Robocop 4 tamanhos de imagem, sendo eles:
- **grid_1** : mantemos o tamanho padrão (sem altura, com de 54px largura);
- **grid_7** : adicionamos uma altura fixa e mantemos a largura padrão;
- **grid_8** : largura de 432px para 210px;
- **grid_9** : 420x110 cortados pelo centro da imagem. alias para <pre><code>grid_9 :width => 420, :height => 110</code></pre>

**Comment by carlosbrando** [comment]
+1
