### ISSUE TITLE
Generator para colocar a config do Dragonfly no initializers

### ISSUE THREAD

**Issue by marcosinger** [marcosinger/attachment_magick#5]

**Comment by carlosbrando** [comment]
Isso é mesmo necessário? Acho que o projeto já vai estar com o config criado quando adicionar o attachment_magick.

**Comment by marcosinger** [comment]
Errei o titulo da issue era "Dragonfly" não "MongoID".
Fiz de uma forma mais fácil do que jogar no initializers.. depois da uma olhada em 

<pre><code> lib/dragonfly/dragonfly_mongo.rb </code></pre>
