### ISSUE TITLE
Display some message if object is not new record

### ISSUE THREAD

**Issue by lucasrenan** [marcosinger/attachment_magick#8]
Display some message if object is not new record in helpers, for inform users that the upload is just possible if doc is saved.

**Comment by marcosinger** [comment]
Lucas, it would be really helpful, but I'm thinking about a new feature: uploading images to new documents, without the need to save before. what do you think?

**Comment by lucasrenan** [comment]
Really, I don't know.. this kind of change in architecture can break compatible with older releases.

**Comment by marcosinger** [comment]
Evolution, my brother.. who do not want this behavior, freeze the Gemfile in 0.2.2 version .. no agree?

**Comment by lucasrenan** [comment]
maybe you are right =)
